### ISSUE TITLE
This is not actually going to merk half the universe.

### ISSUE THREAD

**Issue by multiojuice** [tbg10101/didthanoskill.me#4]
The issue with using random numbers is that it will not actually be 50/50, as Thanos intended his judgement to be. You need to setup a service that is keeping count of the amount of people who check the website, then make sure that Thanos spares only half the visitors.

Now, if you do it on request that will also not be 100% accurate, for obvious reasons. It will spare half the requests, not have the people/entities checking. So you will also need to implement some sort of biometric to make sure that our visitors are unique, and if they are not you will tell them the same fate Thanos gave them the first time. 

Now, I know biometrics are sort of invasive, so you can also possibly use SSNs or something similar, that is a small implementation detail up to you. Thanks for reading, I look forward to seeing the progress.

**Comment by tbg10101** [comment]
If Thanos wants that kind of precision then he can "do it himself".

![gif](https://media1.tenor.com/images/d4c53f19ecd00f4bc09a536ecfb0cd2e/tenor.gif?itemid=11912873)
